import 'dart:convert';

import 'package:image/image.dart';
import 'package:path/path.dart' as path;

import '../abs/icon_generator.dart';
import '../constants.dart' as constants;
import '../utils.dart' as utils;
import 'web_template.dart';

// This is not yet implemented
// ignore: public_member_api_docs
final metaTagsTemplate = (
  String appleMobileWebAppTitle,
  String appleMobileWebAppStatusBarStyle, {
  bool shouldInsertLIString = false,
}) =>
    '''
  <!--Generated by Launcher Icons-->
  <!--LI-->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="$appleMobileWebAppStatusBarStyle">
  <meta name="apple-mobile-web-app-title" content="$appleMobileWebAppTitle">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <link rel="manifest" href="manifest.json">
  <!--LIEND-->
  <!--Generated by Launcher Icons--END-->
''';

/// Generates Web icons for flutter
class WebIconGenerator extends IconGenerator {
  static const _webIconSizeTemplates = <WebIconTemplate>[
    WebIconTemplate(size: 192),
    WebIconTemplate(size: 512),
    WebIconTemplate(size: 192, maskable: true),
    WebIconTemplate(size: 512, maskable: true),
  ];

  /// Creates an instance of [WebIconGenerator].
  ///
  ///
  WebIconGenerator(IconGeneratorContext context) : super(context, 'Web');

  @override
  bool get isEnabled => context.webConfig?.generate ?? false;

  /// Web root directory honoring `output_path` (default `web`), so flavors
  /// can target separate web roots (#426).
  String get _webDirPath => context.webConfig?.outputPath ?? 'web';

  /// All web file paths resolved under [_webDirPath].
  String get _manifestFilePath => path.join(_webDirPath, 'manifest.json');
  String get _indexFilePath => path.join(_webDirPath, 'index.html');
  String get _faviconFilePath => path.join(_webDirPath, 'favicon.png');
  String get _faviconIcoFilePath => path.join(_webDirPath, 'favicon.ico');
  String get _iconsDirPath => path.join(_webDirPath, 'icons');

  @override
  Future<void> createIcons() async {
    final imgFilePath = path.join(
      context.prefixPath,
      context.webConfig!.imagePath ?? context.config.imagePath!,
    );

    // load and decode the image file
    context.logger
        .verbose('Decoding and loading image file at $imgFilePath...');
    final imgFile = await utils.decodeImageFile(imgFilePath);

    // resolve the favicon image path and file, which is either one explicitly
    // provided or the same as the image file loaded above
    late final String faviconImgFilePath;
    late final Image faviconImgFile;
    final faviconImagePathOverride = context.webConfig!.imagePathFavicon;
    if (faviconImagePathOverride != null) {
      // favicon override was specified, construct the full path and decode
      faviconImgFilePath =
          path.join(context.prefixPath, faviconImagePathOverride);
      final faviconImageFile = await utils.decodeImageFile(faviconImgFilePath);
      faviconImgFile = faviconImageFile;
    } else {
      // no favicon override, use the fallback image file
      faviconImgFilePath = imgFilePath;
      faviconImgFile = imgFile;
    }

    // generate favicon in web/favicon.png
    context.logger.verbose('Generating favicon from $faviconImgFilePath...');
    await _generateFavicon(faviconImgFile);

    // generate icons in web/icons/
    context.logger.verbose('Generating icons from $imgFilePath...');
    await _generateIcons(imgFile);

    // update manifest.json in <web root>/manifest.json
    context.logger.verbose(
      'Updating ${path.join(context.prefixPath, _manifestFilePath)}...',
    );
    await _updateManifestFile();

    // TODO(RatakondalaArun): update index.html in web/index.html
    // as we are using flutter default config we no need
    // to update index.html for now
    // _updateIndexFile();
  }

  @override
  bool validateRequirements() {
    // check if web config exists
    context.logger.verbose('Checking webconfig...');
    final webConfig = context.webConfig;
    if (webConfig == null || !webConfig.generate) {
      context.logger.verbose(
        'Web config is not provided or generate is false. Skipped...',
      );
      return false;
    }
    if (webConfig.imagePath == null && context.config.imagePath == null) {
      context.logger
          .verbose('Invalid config. Either provide web.imagePath or imagePath');
      return false;
    }

    // verify web platform related files and directories exists
    final entitesToCheck = [
      path.join(context.prefixPath, _webDirPath),
      path.join(context.prefixPath, _manifestFilePath),
      path.join(context.prefixPath, _indexFilePath),
    ];

    // web platform related files must exist to continue
    final failedEntityPath = utils.areFSEntiesExist(entitesToCheck);
    if (failedEntityPath != null) {
      context.logger.error(
        '$failedEntityPath this file or folder is required to generate web icons',
      );
    }

    return true;
  }

  Future<void> _generateFavicon(Image image) async {
    final size = context.webConfig?.faviconSize ?? constants.kFaviconSize;
    final favIcon = utils.createResizedImage(
      size > 0 ? size : constants.kFaviconSize,
      image,
    );
    final favIconFile = await utils.createFileIfNotExist(
      path.join(context.prefixPath, _faviconFilePath),
    );
    await favIconFile.writeAsBytes(encodePng(favIcon));
    // Browsers request /favicon.ico by default; emit it alongside (#540).
    // index.html keeps pointing at favicon.png, either file now resolves.
    final favIcoFile = await utils.createFileIfNotExist(
      path.join(context.prefixPath, _faviconIcoFilePath),
    );
    await favIcoFile.writeAsBytes(encodeIco(favIcon));
  }

  Future<void> _generateIcons(Image image) async {
    final iconsDir = await utils.createDirIfNotExist(
      path.join(context.prefixPath, _iconsDirPath),
    );
    // generate icons
    for (final template in _webIconSizeTemplates) {
      final resizedImg = utils.createResizedImage(template.size, image);
      final iconFile = await utils.createFileIfNotExist(
        path.join(context.prefixPath, iconsDir.path, template.iconFile),
      );
      await iconFile.writeAsBytes(encodePng(resizedImg));
    }
  }

  Future<void> _updateManifestFile() async {
    final manifestFile = await utils.createFileIfNotExist(
      path.join(context.prefixPath, _manifestFilePath),
    );
    final manifestConfig =
        jsonDecode(await manifestFile.readAsString()) as Map<String, dynamic>;

    // update background_color
    if (context.webConfig?.backgroundColor != null) {
      manifestConfig['background_color'] = context.webConfig?.backgroundColor;
    }

    // update theme_color
    if (context.webConfig?.themeColor != null) {
      manifestConfig['theme_color'] = context.webConfig?.themeColor;
    }

    // replace existing icons to eliminate conflicts
    manifestConfig
      ..remove('icons')
      ..['icons'] = _webIconSizeTemplates
          .map<Map<String, dynamic>>((e) => e.iconManifest)
          .toList();

    await manifestFile.writeAsString(utils.prettifyJsonEncode(manifestConfig));
  }
}
