# Runs the full test suite and the analyzer for any PR opened to merge into the main branch.
#
# This helps ensure we avoid breaking existing functionality and stick to the rules
# defined in the analysis_options.yaml file
name: run tests & analyzer for new pr

on:
  pull_request:
    branches: [ main ]

  # allows for this workflow to be run manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          persist-credentials: false
      - uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d # v1.8.1
      - name: get dependencies
        run: dart pub get
      - name: run tests
        run: dart test
      - name: run analyzer
        run: dart analyze --fatal-infos
